name: Openshift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: '>= 1.20'
      id: go

    - name: Setup Node / NPM
      if: runner.os == 'Linux'
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Docker Build
      if: runner.os == 'Linux'
      run: make docker-openshift
