name: Publish Release

on:
  tags:
    - v1.*

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate Code
      run: make admin && make client

    - name: Build
      run: make build

    - name: Check
      run: make check

    - name: Docker
      run: make docker

    - name: Docker Push
      run: make release-push
